package it.comune.trieste.ouf.ingestion;

import static org.assertj.core.api.Assertions.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.Test;

class ExternalAdaptersTest {
  @Test void jsonPagesOnlyThroughGatewayAndResumesInsidePage(){AtomicInteger calls=new AtomicInteger();RuntimePorts.GatewaySourcePort gateway=(ref,request,corr)->{calls.incrementAndGet();assertThat(ref).startsWith("gateway://");return (request.containsKey("pageToken")?"{\"items\":[{\"id\":3}]}":"{\"items\":[{\"id\":1},{\"id\":2}],\"nextPageToken\":\"p2\"}").getBytes(StandardCharsets.UTF_8);};var adapter=new GatewayJsonAdapter(gateway,new ObjectMapper());ExecutionBundle b=jsonBundle();AdapterSpi.Checkpoint cp;try(var c=adapter.open(b,new AdapterSpi.Checkpoint(Map.of()))){assertThat(c.next().orElseThrow().payload()).containsEntry("id",1);cp=c.checkpoint();}try(var resumed=adapter.open(b,cp)){assertThat(resumed.next().orElseThrow().payload()).containsEntry("id",2);assertThat(resumed.next().orElseThrow().payload()).containsEntry("id",3);assertThat(resumed.next()).isEmpty();}assertThat(calls).hasValue(3);}
  @Test void rawUrlOrCredentialConfigurationIsRejectedBeforeGatewayCall(){RuntimePorts.GatewaySourcePort never=(r,q,c)->{throw new AssertionError("must not call gateway");};var adapter=new GatewayJsonAdapter(never,new ObjectMapper());ExecutionBundle raw=new ExecutionBundle("b","1","h","s","REST_JSON","https://source.example",jsonConfig());assertThatThrownBy(()->adapter.open(raw,null)).hasMessage("ING_GATEWAY_BINDING_REQUIRED");Map<String,Object> c=new HashMap<>(jsonConfig());c.put("accessToken","secret");ExecutionBundle secret=new ExecutionBundle("b","1","h","s","REST_JSON","gateway://binding/1",c);assertThatThrownBy(()->adapter.open(secret,null)).hasMessage("ING_RAW_ROUTE_FORBIDDEN");}
  @Test void gatewayFaultKeepsItsSafeClassification(){RuntimePorts.GatewaySourcePort unavailable=(r,q,c)->{throw new RuntimePorts.GatewayFailure("ING_GATEWAY_503",AdapterSpi.ErrorClass.TRANSIENT_SOURCE);};var cursor=new GatewayJsonAdapter(unavailable,new ObjectMapper()).open(jsonBundle(),null);assertThatThrownBy(cursor::next).isInstanceOf(AdapterSpi.AdapterException.class).extracting(e->((AdapterSpi.AdapterException)e).errorClass()).isEqualTo(AdapterSpi.ErrorClass.TRANSIENT_SOURCE);}
  @Test void gateway429PreservesRetryAfter(){RuntimePorts.GatewaySourcePort limited=(r,q,c)->{throw new RuntimePorts.GatewayFailure("ING_GATEWAY_429",AdapterSpi.ErrorClass.TRANSIENT_SOURCE,Duration.ofSeconds(90));};var cursor=new GatewayJsonAdapter(limited,new ObjectMapper()).open(jsonBundle(),null);AdapterSpi.AdapterException failure=catchThrowableOfType(cursor::next,AdapterSpi.AdapterException.class);assertThat(failure.code()).isEqualTo("ING_GATEWAY_429");assertThat(failure.retryAfter()).contains(Duration.ofSeconds(90));}
  @Test void wfsCapturesCrsAndAxisEvidenceAndRejectsDoctype(){String xml="<wfs:FeatureCollection xmlns:wfs='http://www.opengis.net/wfs/2.0' xmlns:gml='http://www.opengis.net/gml/3.2' xmlns:x='urn:test'><wfs:member><x:road gml:id='r1'><x:name>Main</x:name><x:shape srsName='urn:ogc:def:crs:EPSG::4326'>1 2</x:shape></x:road></wfs:member></wfs:FeatureCollection>";RuntimePorts.GatewaySourcePort gateway=(r,q,c)->xml.getBytes(StandardCharsets.UTF_8);var adapter=new GatewayWfsAdapter(gateway);Map<String,Object> cfg=new HashMap<>();cfg.put("typeName","x:road");cfg.put("typeCode","ROAD");cfg.put("identityFields",List.of("name"));cfg.put("axisOrder","AUTHORITY");cfg.put("pageSize",10);try(var cursor=adapter.open(new ExecutionBundle("b","1","h","s","WFS","gateway://wfs/roads",cfg),null)){var record=cursor.next().orElseThrow();assertThat(record.provenance()).containsEntry("axisOrder","AUTHORITY").containsEntry("srsName","urn:ogc:def:crs:EPSG::4326");assertThat(cursor.next()).isEmpty();}String evil="<!DOCTYPE x [<!ENTITY e SYSTEM 'file:///etc/passwd'>]><x/>";RuntimePorts.GatewaySourcePort bad=(r,q,c)->evil.getBytes(StandardCharsets.UTF_8);assertThatThrownBy(()->new GatewayWfsAdapter(bad).open(new ExecutionBundle("b","1","h","s","WFS","gateway://wfs/roads",cfg),null).next()).hasMessage("ING_WFS_XML_INVALID");}
  private static ExecutionBundle jsonBundle(){return new ExecutionBundle("b","1","h","s","REST_JSON","gateway://rest/objects",jsonConfig());}
  private static Map<String,Object> jsonConfig(){Map<String,Object> c=new HashMap<>();c.put("identityFields",List.of("id"));c.put("typeCode","OBJECT");c.put("pageSize",2);return c;}
}
