package it.comune.trieste.ouf.ingestion;

import static org.assertj.core.api.Assertions.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.test.context.*;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.*;

@SpringBootTest @Import(QuarantineRuntimeTest.ActiveBundleConfig.class) class QuarantineRuntimeTest {
  @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->required("OUF_ING_DB_URL"));r.add("spring.datasource.username",()->required("OUF_ING_DB_USER"));r.add("spring.datasource.password",()->required("OUF_ING_DB_PASSWORD"));}
  @Autowired QuarantineService quarantine;@Autowired TrustedAuthorizationContext authorization;@Autowired JdbcClient sql;
  @Test void payloadReferenceIsNotExposedAndReplayFollowsNormativeTransitions(){UUID run=run(),attempt=attempt(run);UUID q=quarantine.quarantine(run,attempt,"native-person-key","ING_MAPPING_NOT_APPLICABLE","object://secret-payload","evidence://safe","corr-q");Map<String,Object> view=quarantine.get(q);assertThat(view).doesNotContainKey("payload_ref").containsEntry("reason_code","ING_MAPPING_NOT_APPLICABLE").containsEntry("lifecycle_state","OPEN");var actor=authorization.require(request("HUMAN_USER",Set.of("ingestion.quarantine.replay")),"ingestion.quarantine.replay",true);Map<String,Object> preview=quarantine.preview(q,actor);assertThat(preview).doesNotContainKeys("payload_ref","source_object_id").containsEntry("reasonCode","ING_MAPPING_NOT_APPLICABLE");assertThat(String.valueOf(preview.get("sourceObjectFingerprint"))).hasSize(64);quarantine.markRetryReady(q,0,actor,"corr-ready");assertThat(quarantine.get(q)).containsEntry("lifecycle_state","RETRY_READY").containsEntry("lifecycle_version",1L);UUID replay=quarantine.requestReplay(q,"bundle://source/7",actor,"corr-r");assertThat(replay).isNotNull();assertThat(quarantine.get(q)).containsEntry("state","REPLAY_REQUESTED").containsEntry("lifecycle_state","REPROCESSING").containsEntry("lifecycle_version",2L);assertThat(sql.sql("select count(*) from ouf_ingestion.audit_event where resource_id=:i and tenant_id='tenant-a'").param("i",q.toString()).query(Long.class).single()).isEqualTo(2);}
  @Test void humanCanDismissOpenItemWithOptimisticLifecycleLock(){UUID run=run(),attempt=attempt(run),q=quarantine.quarantine(run,attempt,"object","ING_DATA_INVALID","object://secret","evidence://safe","corr");var actor=new TrustedAuthorizationContext.Context("human:operator","HUMAN_USER","tenant-a",Set.of(),"decision://42");quarantine.close(q,"DISMISSED","not actionable",null,0,actor,"corr-close");assertThat(quarantine.get(q)).containsEntry("lifecycle_state","DISMISSED").containsEntry("lifecycle_version",1L).containsEntry("resolution_reason","not actionable");assertThatThrownBy(()->quarantine.close(q,"DISMISSED","again",null,0,actor,"corr-close")).hasMessageContaining("CONFLICT");}
  @Test void supersedeRequiresReplacementAndTenantScopeIsEnforced(){UUID run=run(),attempt=attempt(run),q=quarantine.quarantine(run,attempt,"object","ING_DATA_INVALID","object://secret","evidence://safe","corr");var actor=new TrustedAuthorizationContext.Context("human:operator","HUMAN_USER","tenant-a",Set.of(),"decision://42");assertThatThrownBy(()->quarantine.close(q,"SUPERSEDED","replaced",null,0,actor,"corr")).isInstanceOf(IllegalArgumentException.class);quarantine.close(q,"SUPERSEDED","replaced","quarantine:new",0,actor,"corr");assertThat(quarantine.get(q)).containsEntry("lifecycle_state","SUPERSEDED").containsEntry("superseded_by","quarantine:new");assertThatThrownBy(()->quarantine.preview(q,new TrustedAuthorizationContext.Context("human:other","HUMAN_USER","tenant-b",Set.of(),"decision:b"))).hasMessageContaining("NOT_FOUND");}
  @Test void actorHeadersCannotSubstituteServerEstablishedPrincipal(){MockHttpServletRequest r=new MockHttpServletRequest();r.addHeader("X-Actor-Subject","forged");r.addHeader("X-Capabilities","ingestion.quarantine.replay");assertThatThrownBy(()->authorization.resolve(r)).hasMessageContaining("403");}
  @Test void replayModesPinHistoricalCurrentOrExplicitTargetAndAreIdempotent(){var actor=new TrustedAuthorizationContext.Context("human:operator","HUMAN_USER","tenant-a",Set.of(),"decision://42");UUID reproduce=ready(actor),current=ready(actor),target=ready(actor);UUID r1=quarantine.requestReplay(reproduce,"REPRODUCE",null,actor,"corr-reproduce");UUID duplicate=quarantine.requestReplay(reproduce,"REPRODUCE",null,actor,"corr-duplicate");assertThat(duplicate).isEqualTo(r1);assertThat(replay(r1)).containsEntry("replay_mode","REPRODUCE").containsEntry("original_bundle_ref","b:1:sha256:x").containsEntry("target_bundle_ref","b:1:sha256:x");UUID r2=quarantine.requestReplay(current,"REPROCESS_CURRENT",null,actor,"corr-current");assertThat(replay(r2)).containsEntry("target_bundle_ref","current:9:sha256:current");UUID r3=quarantine.requestReplay(target,"REPROCESS_TARGET","bundle:target:4:sha256:target",actor,"corr-target");assertThat(replay(r3)).containsEntry("replay_mode","REPROCESS_TARGET").containsEntry("target_bundle_ref","bundle:target:4:sha256:target");}
  private UUID ready(TrustedAuthorizationContext.Context actor){UUID run=run(),attempt=attempt(run),q=quarantine.quarantine(run,attempt,"object","ING_DATA_INVALID","raw://"+run,"evidence://safe","corr");quarantine.markRetryReady(q,0,actor,"corr-ready");return q;}
  private Map<String,Object> replay(UUID id){return sql.sql("select replay_mode,original_bundle_ref,target_bundle_ref,raw_object_ref,parent_attempt_id from ouf_ingestion.replay_request where replay_id=:r").param("r",id).query().singleRow();}
  private UUID run(){UUID id=UUID.randomUUID();sql.sql("insert into ouf_ingestion.ing_run(run_id,source_id,bundle_id,bundle_version,bundle_checksum,mode,state,correlation_id,tenant_id) values(:i,:s,'b','1','sha256:x','REPLAY','RUNNING','corr','tenant-a')").param("i",id).param("s","source-"+id).update();return id;}
  private UUID attempt(UUID run){UUID id=UUID.randomUUID();sql.sql("insert into ouf_ingestion.processing_attempt(attempt_id,run_id,source_object_id,attempt_no,adapter_id,bundle_version,state) values(:i,:r,'native-person-key',1,'test','1','FAILED')").param("i",id).param("r",run).update();return id;}
  private MockHttpServletRequest request(String type,Set<String> capabilities){MockHttpServletRequest r=new MockHttpServletRequest();r.setUserPrincipal(()->"human:operator");r.setAttribute(TrustedAuthorizationContext.ACTOR_TYPE,type);r.setAttribute(TrustedAuthorizationContext.TENANT,"tenant-a");r.setAttribute(TrustedAuthorizationContext.DECISION,"decision://42");r.setAttribute(TrustedAuthorizationContext.CAPABILITIES,capabilities);return r;}
  private static String required(String n){String v=System.getenv(n);if(v==null)throw new IllegalStateException(n+" required");return v;}
  @TestConfiguration static class ActiveBundleConfig {@Bean RuntimePorts.ActiveBundlePort activeBundlePort(){return source->new ExecutionBundle("current","9","sha256:current",source,"REST_JSON","gateway://current",Map.of());}}
}
