package it.comune.trieste.ouf.ingestion;

import static org.assertj.core.api.Assertions.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.test.context.*;

@SpringBootTest class RunControlRuntimeTest {
  @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->required("OUF_ING_DB_URL"));r.add("spring.datasource.username",()->required("OUF_ING_DB_USER"));r.add("spring.datasource.password",()->required("OUF_ING_DB_PASSWORD"));}
  @Autowired RunStateRepository state;@Autowired JdbcClient sql;@Autowired ObjectMapper json;@Autowired PlatformTransactionManager transactions;
  @Test void everyDispatchedRunPinsBundleAndPassesPreflightBeforeRunning(){String source=schedule("tenant-a");AtomicInteger checks=new AtomicInteger();RuntimePorts.ActiveBundlePort bundles=id->bundle(id);RuntimePorts.SemanticPort semantic=refs->{assertThat(refs).containsExactly("schema://1","semantic://set/7");checks.incrementAndGet();};RunCoordinator coordinator=new RunCoordinator(state,bundles,semantic);UUID run=coordinator.dispatchOne("worker-a").orElseThrow();assertThat(checks).hasValue(1);assertThat(state.run(run)).containsEntry("state","RUNNING").containsEntry("phase","FULL_SNAPSHOT").containsEntry("bundle_checksum","sha256:pinned").containsEntry("tenant_id","tenant-a");assertThat(state.claimDue("worker-b",Duration.ofMinutes(1))).isEmpty();}
  @Test void phasesOnlyAdvanceInNormativeOrder(){String source=schedule("tenant-phase");var claim=state.claimDue("phase-worker",Duration.ofMinutes(1)).orElseThrow();UUID run=state.createPreflightRun(claim,bundle(source),"corr");state.preflightSucceeded(run);assertThatThrownBy(()->state.advancePhase(run,"DELTA")).hasMessage("ING_PHASE_TRANSITION_INVALID");state.advancePhase(run,"CATCH_UP");state.advancePhase(run,"DELTA");assertThat(state.run(run)).containsEntry("phase","DELTA");state.releaseSchedule(claim,true);}
  @Test void onlyTransientFailuresConsumeFiniteWindowAndSuccessRecovers(){String source="health-"+UUID.randomUUID();for(int i=0;i<5;i++)state.recordFailure(source,"ING_GATEWAY_503",AdapterSpi.ErrorClass.TRANSIENT_SOURCE,null);Map<String,Object> paused=sql.sql("select status,consecutive_failures,retry_attempts_in_window,last_error_code,circuit_open_until,retry_not_before,first_failure_at,last_failure_at from ouf_ingestion.source_health where source_id=:s").param("s",source).query().singleRow();assertThat(paused).containsEntry("status","PAUSED").containsEntry("consecutive_failures",5).containsEntry("retry_attempts_in_window",5).containsEntry("last_error_code","ING_GATEWAY_503");assertThat(paused.get("circuit_open_until")).isNotNull();assertThat(paused.get("retry_not_before")).isNotNull();assertThat(paused.get("first_failure_at")).isNotNull();assertThat(paused.get("last_failure_at")).isNotNull();state.recordSuccess(source);assertThat(sql.sql("select status||':'||retry_attempts_in_window from ouf_ingestion.source_health where source_id=:s").param("s",source).query(String.class).single()).isEqualTo("HEALTHY:0");}
  @Test void deterministicDataFailuresNeverIncrementOrOpenCircuit(){String source="data-"+UUID.randomUUID();for(int i=0;i<8;i++)state.recordFailure(source,"ING_SCHEMA_INCOMPATIBLE",AdapterSpi.ErrorClass.DATA,null);Map<String,Object> health=sql.sql("select status,consecutive_failures,circuit_open_until,retry_not_before from ouf_ingestion.source_health where source_id=:s").param("s",source).query().singleRow();assertThat(health).containsEntry("status","DEGRADED").containsEntry("consecutive_failures",0).containsEntry("circuit_open_until",null).containsEntry("retry_not_before",null);}
  @Test void retryAfterSuppressesSchedulingAndRecoveryProbeIsExclusive(){String source=schedule("tenant-retry");state.recordFailure(source,"ING_GATEWAY_429",AdapterSpi.ErrorClass.TRANSIENT_SOURCE,Duration.ofMinutes(5));assertThat(state.claimDue("early",Duration.ofMinutes(1))).isEmpty();sql.sql("update ouf_ingestion.source_health set status='PAUSED',consecutive_failures=5,retry_not_before=transaction_timestamp()-interval '1 second',circuit_open_until=transaction_timestamp()-interval '1 second' where source_id=:s").param("s",source).update();var claim=state.claimDue("probe-worker",Duration.ofMinutes(1)).orElseThrow();assertThat(sql.sql("select recovery_probe_owner from ouf_ingestion.source_health where source_id=:s").param("s",source).query(String.class).single()).isEqualTo("probe-worker");assertThat(state.claimDue("other-worker",Duration.ofMinutes(1))).isEmpty();state.releaseSchedule(claim,false);}
  @Test void expiredRetryWindowStartsANewBudget(){String source="window-"+UUID.randomUUID();state.recordFailure(source,"ING_GATEWAY_503",AdapterSpi.ErrorClass.TRANSIENT_SOURCE,null);sql.sql("update ouf_ingestion.source_health set retry_window_started_at=transaction_timestamp()-interval '1 hour',retry_window_seconds=60,retry_attempts_in_window=4 where source_id=:s").param("s",source).update();state.recordFailure(source,"ING_GATEWAY_503",AdapterSpi.ErrorClass.TRANSIENT_SOURCE,null);assertThat(sql.sql("select retry_attempts_in_window from ouf_ingestion.source_health where source_id=:s").param("s",source).query(Integer.class).single()).isEqualTo(1);assertThat(sql.sql("select circuit_open_until is null from ouf_ingestion.source_health where source_id=:s").param("s",source).query(Boolean.class).single()).isTrue();}
  @Test void pressureStateUsesHysteresisAndPolicyDefaults(){sql.sql("update ouf_ingestion.runtime_pressure_policy set global_running_limit=8 where policy_key='GLOBAL'").update();assertThat(sql.sql("select global_running_limit from ouf_ingestion.runtime_pressure_policy where policy_key='GLOBAL'").query(Integer.class).single()).isEqualTo(8);int backlog=sql.sql("select count(*) from ouf_ingestion.handoff_outbox where state<>'ACKED'").query(Integer.class).single();sql.sql("update ouf_ingestion.runtime_pressure_policy set state='HARD_PRESSURE',recovery_outbox_limit=:r,soft_outbox_limit=:s,hard_outbox_limit=:h where policy_key='GLOBAL'").param("r",backlog+1).param("s",backlog+2).param("h",backlog+3).update();assertThat(state.refreshPressure()).isEqualTo("RECOVERY");assertThat(state.refreshPressure()).isEqualTo("NORMAL");sql.sql("update ouf_ingestion.runtime_pressure_policy set global_running_limit=128,soft_outbox_limit=1000,hard_outbox_limit=5000,recovery_outbox_limit=500 where policy_key='GLOBAL'").update();}
  @Test void pauseResumePreservesPinnedBaselineAndAbortIsTerminal(){String source=schedule("tenant-control");var claim=state.claimDue("control-worker",Duration.ofMinutes(1)).orElseThrow();UUID run=state.createPreflightRun(claim,bundle(source),"corr-control");state.preflightSucceeded(run);sql.sql("update ouf_ingestion.ing_partition set checkpoint_json='{\"ordinal\":7}',committed_watermark_json='{\"ordinal\":5}' where run_id=:r").param("r",run).update();List<String> verified=new ArrayList<>();RunLifecycleService controls=new RunLifecycleService(sql,json,refs->verified.addAll(refs),transactions);var actor=new TrustedAuthorizationContext.Context("human:operator","HUMAN_USER","tenant-control",Set.of(),"decision://control");
    assertThat(controls.pause(run,0,actor,"corr-pause")).containsEntry("state","PAUSED").containsEntry("control_version",1L);assertThat(controls.resume(run,1,actor,"corr-resume")).containsEntry("state","RUNNING").containsEntry("control_version",2L);assertThat(verified).containsExactly("schema://1","semantic://set/7");assertThat(sql.sql("select checkpoint_json::text||':'||committed_watermark_json::text from ouf_ingestion.ing_partition where run_id=:r").param("r",run).query(String.class).single()).contains("7","5");assertThat(controls.abort(run,2,actor,"corr-abort")).containsEntry("state","ABORTED").containsEntry("control_version",3L);assertThat(sql.sql("select state from ouf_ingestion.ing_partition where run_id=:r").param("r",run).query(String.class).single()).isEqualTo("ABORTED");assertThatThrownBy(()->controls.resume(run,3,actor,"corr-invalid")).hasMessage("ING_RUN_NOT_PAUSED");assertThat(sql.sql("select event_type from ouf_ingestion.audit_event where resource_id=:r order by created_at").param("r",run.toString()).query(String.class).list()).containsExactly("RUN_PAUSED","RUN_RESUMED","RUN_ABORTED");state.releaseSchedule(claim,true);}
  private String schedule(String tenant){sql.sql("update ouf_ingestion.runtime_pressure_policy set global_running_limit=128 where policy_key='GLOBAL'").update();String source="source-"+UUID.randomUUID();sql.sql("insert into ouf_ingestion.ing_schedule(schedule_id,tenant_id,source_id,interval_seconds,next_run_at) values(:i,:t,:s,60,transaction_timestamp()-interval '1 minute')").param("i",UUID.randomUUID()).param("t",tenant).param("s",source).update();return source;}
  private static ExecutionBundle bundle(String source){return new ExecutionBundle("bundle-1","7","sha256:pinned",source,"REST_JSON","gateway://binding/1",Map.of("pinnedReferences",List.of("schema://1","semantic://set/7")));}
  private static String required(String n){String v=System.getenv(n);if(v==null)throw new IllegalStateException(n+" required");return v;}
}
