package it.comune.trieste.ouf.ingestion;

import static org.assertj.core.api.Assertions.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.*;

@SpringBootTest class RunExecutionWorkerRuntimeTest {
  @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->required("OUF_ING_DB_URL"));r.add("spring.datasource.username",()->required("OUF_ING_DB_USER"));r.add("spring.datasource.password",()->required("OUF_ING_DB_PASSWORD"));}
  @Autowired RunStateRepository state;@Autowired RunExecutionRepository execution;@Autowired DurablePipelineRepository durable;@Autowired QuarantineService quarantine;@Autowired FrozenContractValidator validator;@Autowired SchemaSurveillanceService schemas;@Autowired ObjectMapper json;@Autowired JdbcClient sql;

  @Test void pinnedSnapshotRunsThroughAdapterPipelineDrainingAndAckCompletion(){
    String source="source-"+UUID.randomUUID();ExecutionBundle bundle=bundle(source);var claim=new RunStateRepository.ScheduleClaim(UUID.randomUUID(),"tenant-1",source,300,"scheduler");UUID run=state.createPreflightRun(claim,bundle,"corr-worker");state.preflightSucceeded(run);sql.sql("update ouf_ingestion.ing_run set created_at='2000-01-01T00:00:00Z' where run_id=:r").param("r",run).update();
    RecordingLake lake=new RecordingLake();CanonicalRecordPipeline pipeline=new CanonicalRecordPipeline(json,validator,durable,quarantine,lake,Clock.fixed(Instant.parse("2026-01-01T00:00:00Z"),ZoneOffset.UTC));AdapterSpi adapter=new OneRecordAdapter();RunExecutionWorker worker=new RunExecutionWorker(execution,b->adapter,pipeline,schemas,state);
    assertThat(worker.executeOne("worker-1")).contains(run);assertThat(state.run(run).get("state")).isEqualTo("DRAINING");assertThat(lake.zones).containsExactly(RuntimePorts.DataLakePort.Zone.RAW,RuntimePorts.DataLakePort.Zone.NORMALIZED,RuntimePorts.DataLakePort.Zone.CURATED);
    var handoff=durable.claim("dispatcher",Duration.ofMinutes(1)).orElseThrow();durable.acknowledge(handoff.handoffId(),"dispatcher","udp:receipt");worker.executeOne("worker-1");
    assertThat(state.run(run).get("state")).isEqualTo("SUCCEEDED");assertThat(sql.sql("select state from ouf_ingestion.ing_partition where run_id=:r").param("r",run).query(String.class).single()).isEqualTo("SUCCEEDED");assertThat(execution.bundle(run)).isEqualTo(bundle);
  }
  @Test void incompatibleShapeIsObservedIssuedLoggedQuarantinedAndPausesOnlyItsRun(){
    String source="source-"+UUID.randomUUID();ExecutionBundle bundle=bundle(source);UUID run=state.createPreflightRun(new RunStateRepository.ScheduleClaim(UUID.randomUUID(),"tenant-1",source,300,"scheduler"),bundle,"corr-drift");state.preflightSucceeded(run);sql.sql("update ouf_ingestion.ing_run set created_at='1999-01-01T00:00:00Z' where run_id=:r").param("r",run).update();
    RecordingLake lake=new RecordingLake();CanonicalRecordPipeline pipeline=new CanonicalRecordPipeline(json,validator,durable,quarantine,lake,Clock.systemUTC());AdapterSpi adapter=new OneRecordAdapter(Map.of("unexpected","value"),Map.of("managedObjectRef","managed:object"));new RunExecutionWorker(execution,b->adapter,pipeline,schemas,state).executeOne("worker-drift");
    assertThat(state.run(run).get("state")).isEqualTo("PAUSED");assertThat(sql.sql("select outcome from ouf_ingestion.schema_observation where run_id=:r").param("r",run).query(String.class).single()).isEqualTo("INCOMPATIBLE");assertThat(sql.sql("select count(*) from ouf_ingestion.runtime_issue where run_id=:r and issue_code='ING_SCHEMA_INCOMPATIBLE'").param("r",run).query(Long.class).single()).isOne();assertThat(sql.sql("select count(*) from ouf_ingestion.ing_quarantine where run_id=:r and reason_code='ING_SCHEMA_INCOMPATIBLE'").param("r",run).query(Long.class).single()).isOne();assertThat(sql.sql("select count(*) from ouf_ingestion.handoff_outbox where run_id=:r").param("r",run).query(Long.class).single()).isZero();assertThat(sql.sql("select count(*) from ouf_ingestion.operational_event where run_id=:r and event_type='SCHEMA_DRIFT_OPEN'").param("r",run).query(Long.class).single()).isOne();
  }
  @Test void gateway429FeedsTransientHealthAndHonorsRetryAfter(){
    String source="source-"+UUID.randomUUID();ExecutionBundle bundle=bundle(source);UUID run=state.createPreflightRun(new RunStateRepository.ScheduleClaim(UUID.randomUUID(),"tenant-1",source,300,"scheduler"),bundle,"corr-429");state.preflightSucceeded(run);sql.sql("update ouf_ingestion.ing_run set created_at='1900-01-01T00:00:00Z' where run_id=:r").param("r",run).update();
    RecordingLake lake=new RecordingLake();CanonicalRecordPipeline pipeline=new CanonicalRecordPipeline(json,validator,durable,quarantine,lake,Clock.systemUTC());AdapterSpi adapter=new OneRecordAdapter(){@Override public RecordCursor open(ExecutionBundle b,Checkpoint c){return new RecordCursor(){public Optional<SourceRecord> next(){throw new AdapterException("ING_GATEWAY_429",ErrorClass.TRANSIENT_SOURCE,"ING_GATEWAY_429",Duration.ofMinutes(4));}public Checkpoint checkpoint(){return new Checkpoint(Map.of());}public void close(){}};}};
    new RunExecutionWorker(execution,b->adapter,pipeline,schemas,state).executeOne("worker-429");
    Map<String,Object> health=sql.sql("select status,consecutive_failures,last_error_code,retry_not_before>transaction_timestamp()+interval '3 minutes' as retry_honored from ouf_ingestion.source_health where source_id=:s").param("s",source).query().singleRow();
    assertThat(health).containsEntry("status","DEGRADED").containsEntry("consecutive_failures",1).containsEntry("last_error_code","ING_GATEWAY_429").containsEntry("retry_honored",true);
  }
  private static ExecutionBundle bundle(String source){Map<String,Object> cfg=new LinkedHashMap<>(Map.ofEntries(Map.entry("sourceSchemaRef","schema:places:1"),Map.entry("sourceSchemaId","places"),Map.entry("sourceSchemaVersion","1"),Map.entry("expectedFieldNames",List.of("name")),Map.entry("typeCode","place"),Map.entry("semanticPublicationSetRef","sem:1"),Map.entry("adapterProfileRef","adapter:test:1"),Map.entry("adapterId","test-adapter"),Map.entry("adapterRuntimeVersion","1.0.0"),Map.entry("observationPolicy","ACQUISITION_TIME"),Map.entry("propertyMappings",List.of(Map.of("sourceField","name","targetPropertyIri","https://example.test/name","transform","IDENTITY"))),Map.entry("mappingRefs",List.of("mapping:1")),Map.entry("pinnedReferences",List.of("schema:places:1","sem:1"))));return new ExecutionBundle("bundle","1","sha256:bundle",source,"INTERNAL_MANAGED_CSV","managed:object",cfg);}
  private static class OneRecordAdapter implements AdapterSpi {private final Map<String,Object> payload,provenance;OneRecordAdapter(){this(Map.of("name","Town Hall"),Map.of("managedObjectRef","managed:object"));}OneRecordAdapter(Map<String,Object> payload,Map<String,Object> provenance){this.payload=payload;this.provenance=provenance;}public String adapterId(){return "test-adapter";}public Set<String> acquisitionModes(){return Set.of("INTERNAL_MANAGED_CSV");}public Compatibility compatibility(){return new Compatibility("1.0.0","1.0.0");}public RecordCursor open(ExecutionBundle b,Checkpoint c){return new RecordCursor(){boolean sent;public Optional<SourceRecord> next(){if(sent)return Optional.empty();sent=true;return Optional.of(new SourceRecord("object-1",1,payload,provenance));}public Checkpoint checkpoint(){return new Checkpoint(Map.of("ordinal",sent?1:0));}public void close(){}};}}
  private static final class RecordingLake implements RuntimePorts.DataLakePort {final List<Zone> zones=new ArrayList<>();public Receipt persist(Zone zone,UUID run,String object,byte[] content,String hash,String key){zones.add(zone);return new Receipt("lake:"+zone+":"+key,true);}}
  private static String required(String n){String v=System.getenv(n);if(v==null)throw new IllegalStateException(n+" required");return v;}
}
