package it.comune.trieste.ouf.ingestion;

import static it.comune.trieste.ouf.ingestion.AdapterSpi.*;
import static it.comune.trieste.ouf.ingestion.ExternalAdapterSupport.*;
import java.io.ByteArrayInputStream;
import java.util.*;
import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.*;

public final class GatewayWfsAdapter implements AdapterSpi {
  private final RuntimePorts.GatewaySourcePort gateway;
  public GatewayWfsAdapter(RuntimePorts.GatewaySourcePort gateway){this.gateway=Objects.requireNonNull(gateway);}
  public String adapterId(){return "gateway-wfs-v1";}public Set<String> acquisitionModes(){return Set.of("WFS");}public Compatibility compatibility(){return new Compatibility("1.0.0","1.0.0");}
  public RecordCursor open(ExecutionBundle b,Checkpoint checkpoint){requireGateway(b);return new Cursor(b,checkpoint==null?Map.of():checkpoint.value());}
  private final class Cursor implements RecordCursor {
    private final ExecutionBundle b;private final int count,maxPages,maxRecords,maxBytes;private final String typeName,typeCode,axisOrder,correlation;private final List<String> keys;private final Deque<SourceRecord> buffer=new ArrayDeque<>();private int startIndex,pageOffset,pages,records,ordinal;private boolean loaded,done;
    Cursor(ExecutionBundle b,Map<String,Object> cp){this.b=b;Map<String,Object> c=b.configuration();count=integer(c,"pageSize",100,1,10_000);maxPages=integer(c,"maxPages",1000,1,100_000);maxRecords=integer(c,"maxRecords",100_000,1,1_000_000);maxBytes=integer(c,"maxPageBytes",5_000_000,1,50_000_000);typeName=text(c,"typeName","feature");typeCode=text(c,"typeCode",typeName);axisOrder=text(c,"axisOrder","AUTHORITY");if(!Set.of("AUTHORITY","LON_LAT","LAT_LON").contains(axisOrder))throw error("ING_WFS_AXIS_ORDER_INVALID",ErrorClass.CONFIGURATION);correlation=text(c,"correlationId","runtime");keys=strings(c,"identityFields");startIndex=cp.get("startIndex") instanceof Number n?n.intValue():0;pageOffset=cp.get("pageOffset") instanceof Number n?n.intValue():0;records=cp.get("recordIndex") instanceof Number n?n.intValue():0;ordinal=records;}
    public Optional<SourceRecord> next(){while(buffer.isEmpty()&&!done){if(loaded){startIndex+=count;pageOffset=0;loaded=false;}fetch();}if(buffer.isEmpty())return Optional.empty();records++;pageOffset++;return Optional.of(buffer.removeFirst());}
    private void fetch(){if(++pages>maxPages)throw error("ING_PAGE_LIMIT_EXCEEDED",ErrorClass.DATA);byte[] bytes;try{bytes=gateway.fetch(b.bindingRef(),Map.of("service","WFS","request","GetFeature","typeNames",typeName,"startIndex",startIndex,"count",count),correlation);}catch(RuntimePorts.GatewayFailure e){throw new AdapterException(e.safeCode(),e.errorClass(),e.safeCode(),e.retryAfter().orElse(null));}if(bytes.length>maxBytes)throw error("ING_PAGE_TOO_LARGE",ErrorClass.DATA);List<Element> features=parse(bytes);if(pageOffset>features.size())throw error("ING_CHECKPOINT_OUT_OF_RANGE",ErrorClass.CONFIGURATION);for(int i=pageOffset;i<features.size();i++){if(records+buffer.size()>=maxRecords)throw error("ING_RECORD_LIMIT_EXCEEDED",ErrorClass.DATA);Element feature=features.get(i);Map<String,Object> row=fields(feature);String nativeId=feature.getAttributeNS("http://www.opengis.net/gml","id");String id=nativeId.isBlank()?identity(b.sourceId(),typeCode,row,keys):identity(b.sourceId(),typeCode,Map.of("gmlId",nativeId),List.of("gmlId"));Map<String,Object> provenance=new LinkedHashMap<>();provenance.put("bindingRef",b.bindingRef());provenance.put("startIndex",startIndex);provenance.put("axisOrder",axisOrder);String srs=findAttribute(feature,"srsName");if(srs!=null)provenance.put("srsName",srs);buffer.add(new SourceRecord(id,ordinal++,row,provenance));}loaded=true;done=features.size()<count;}
    public Checkpoint checkpoint(){return new Checkpoint(Map.of("startIndex",startIndex,"pageOffset",pageOffset,"recordIndex",records));}public void close(){buffer.clear();done=true;}
  }
  private static List<Element> parse(byte[] bytes){try{DocumentBuilderFactory f=DocumentBuilderFactory.newInstance();f.setNamespaceAware(true);f.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);f.setFeature("http://xml.org/sax/features/external-general-entities",false);f.setFeature("http://xml.org/sax/features/external-parameter-entities",false);f.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD,"");f.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA,"");Document d=f.newDocumentBuilder().parse(new ByteArrayInputStream(bytes));List<Element> out=new ArrayList<>();NodeList all=d.getElementsByTagNameNS("*","member");if(all.getLength()==0)all=d.getElementsByTagNameNS("*","featureMember");for(int i=0;i<all.getLength();i++){NodeList children=all.item(i).getChildNodes();for(int j=0;j<children.getLength();j++)if(children.item(j) instanceof Element e){out.add(e);break;}}return out;}catch(Exception e){throw error("ING_WFS_XML_INVALID",ErrorClass.DATA);}}
  private static Map<String,Object> fields(Element feature){Map<String,Object> out=new LinkedHashMap<>();NodeList children=feature.getChildNodes();for(int i=0;i<children.getLength();i++)if(children.item(i) instanceof Element e)out.put(e.getLocalName()==null?e.getNodeName():e.getLocalName(),e.getTextContent());return out;}
  private static String findAttribute(Element root,String local){if(root.hasAttribute(local))return root.getAttribute(local);NodeList all=root.getElementsByTagNameNS("*","*");for(int i=0;i<all.getLength();i++){Element e=(Element)all.item(i);if(e.hasAttribute(local))return e.getAttribute(local);}return null;}
}
