package it.comune.trieste.ouf.ingestion;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service
public class HistoricalContractService {
  private final JdbcClient sql;private final ObjectMapper json;public HistoricalContractService(JdbcClient sql,ObjectMapper json){this.sql=sql;this.json=json;}
  public Map<String,Object> runContracts(UUID run,TrustedAuthorizationContext.Context actor){List<Map<String,Object>> rows=sql.sql("select r.run_id,r.source_id,r.bundle_id,r.bundle_version,r.bundle_checksum,s.snapshot_id,coalesce(s.snapshot_json#>>'{configuration,sourceSchemaRef}',s.snapshot_json#>>'{configuration,publishedBundle,extractionProfile,runtime,execution,sourceSchemaRef}') source_schema_ref,coalesce(s.snapshot_json#>>'{configuration,sourceSchemaVersion}',s.snapshot_json#>>'{configuration,publishedBundle,extractionProfile,runtime,execution,sourceSchemaVersion}') source_schema_version,s.snapshot_json#>'{configuration,mappingRefs}' mapping_refs,coalesce(s.snapshot_json#>>'{configuration,semanticPublicationSetRef}',s.snapshot_json#>>'{configuration,publishedBundle,extractionProfile,runtime,execution,semanticPublicationSetRef}') semantic_publication_set_ref,coalesce(s.snapshot_json#>>'{configuration,adapterProfileRef}',s.snapshot_json#>>'{configuration,publishedBundle,extractionProfile,runtime,execution,adapterProfileRef}') adapter_profile_ref,s.created_at from ouf_ingestion.ing_run r join ouf_ingestion.runtime_configuration_snapshot s using(run_id) where r.run_id=:r and r.tenant_id=:t").param("r",run).param("t",actor.tenantId()).query().listOfRows();if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"ING_HISTORICAL_CONTRACT_NOT_FOUND");return Collections.unmodifiableMap(new LinkedHashMap<>(rows.getFirst()));}
  public List<Map<String,Object>> lineage(UUID run,TrustedAuthorizationContext.Context actor,int limit){return sql.sql("select l.lineage_id,l.source_object_id,l.bundle_ref,l.adapter_ref,l.evidence_json#>'{contracts}' contract_refs,l.created_at from ouf_ingestion.ing_lineage l join ouf_ingestion.ing_run r using(run_id) where l.run_id=:r and r.tenant_id=:t order by l.created_at,lineage_id limit :n").param("r",run).param("t",actor.tenantId()).param("n",Math.max(1,Math.min(limit,200))).query().listOfRows();}
  public Map<String,Object> deletionCheck(String reference,TrustedAuthorizationContext.Context actor){String ref=required(reference);long dependencies=sql.sql("select (select count(*) from ouf_ingestion.ing_run r where r.tenant_id=:t and (r.bundle_id||':'||r.bundle_version||':'||r.bundle_checksum)=:ref)+(select count(*) from ouf_ingestion.runtime_configuration_snapshot s join ouf_ingestion.ing_run r using(run_id) where r.tenant_id=:t and jsonb_path_exists(s.snapshot_json,'$.** ? (@ == $ref)',jsonb_build_object('ref',:ref)))+(select count(*) from ouf_ingestion.ing_lineage l join ouf_ingestion.ing_run r using(run_id) where r.tenant_id=:t and (l.bundle_ref=:ref or l.adapter_ref=:ref or jsonb_path_exists(l.evidence_json,'$.** ? (@ == $ref)',jsonb_build_object('ref',:ref))))+(select count(*) from ouf_ingestion.replay_request where tenant_id=:t and (original_bundle_ref=:ref or target_bundle_ref=:ref))").param("t",actor.tenantId()).param("ref",ref).query(Long.class).single();boolean hold=sql.sql("select coalesce((select action='APPLY' from ouf_ingestion.historical_contract_legal_hold_event where tenant_id=:t and contract_ref=:ref order by created_at desc,event_id desc limit 1),false)").param("t",actor.tenantId()).param("ref",ref).query(Boolean.class).single();return Map.of("contractRef",ref,"removable",dependencies==0&&!hold,"dependencyCount",dependencies,"legalHold",hold);}
  public void assertRemovable(String reference,TrustedAuthorizationContext.Context actor){Map<String,Object> result=deletionCheck(reference,actor);if(!Boolean.TRUE.equals(result.get("removable")))throw new ResponseStatusException(HttpStatus.CONFLICT,"ING_HISTORICAL_CONTRACT_DELETE_BLOCKED");}
  @Transactional public void legalHold(String reference,String action,String reason,TrustedAuthorizationContext.Context actor,String correlation){String ref=required(reference);if(!Set.of("APPLY","RELEASE").contains(action)||reason==null||reason.isBlank()||reason.length()>1000)throw new IllegalArgumentException("ING_LEGAL_HOLD_INVALID");sql.sql("insert into ouf_ingestion.historical_contract_legal_hold_event(event_id,contract_ref,action,reason,created_by,tenant_id,authorization_decision_ref) values(:i,:r,:a,:x,:u,:t,:d)").param("i",UUID.randomUUID()).param("r",ref).param("a",action).param("x",reason).param("u",actor.subject()).param("t",actor.tenantId()).param("d",actor.decisionRef()).update();audit("CONTRACT_LEGAL_HOLD_"+action,ref,actor,correlation,Map.of("reason",reason));}
  private void audit(String event,String ref,TrustedAuthorizationContext.Context actor,String correlation,Map<String,Object> detail){try{sql.sql("insert into ouf_ingestion.audit_event(event_id,event_type,actor_subject,actor_type,resource_type,resource_id,correlation_id,detail_json,tenant_id,authorization_decision_ref) values(:i,:e,:a,:t,'HISTORICAL_CONTRACT',:r,:c,cast(:j as jsonb),:n,:d)").param("i",UUID.randomUUID()).param("e",event).param("a",actor.subject()).param("t",actor.actorType()).param("r",ref).param("c",correlation).param("j",json.writeValueAsString(detail)).param("n",actor.tenantId()).param("d",actor.decisionRef()).update();}catch(Exception e){throw new IllegalStateException("ING_AUDIT_WRITE_FAILED",e);}}
  private static String required(String value){if(value==null||value.isBlank()||value.length()>500)throw new IllegalArgumentException("ING_CONTRACT_REF_INVALID");return value;}
}
