package it.comune.trieste.ouf.ingestion;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;
import org.slf4j.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class QuarantineService {
  private static final Logger LOG=LoggerFactory.getLogger(QuarantineService.class);
  private final JdbcClient sql;private final ObjectMapper json;private final IngestionMetrics metrics;
  public QuarantineService(JdbcClient sql,ObjectMapper json,IngestionMetrics metrics){this.sql=sql;this.json=json;this.metrics=metrics;}
  public List<Map<String,Object>> search(String state,int limit){if(!Set.of("OPEN","REPLAY_REQUESTED","RELEASED","REJECTED").contains(state))throw new IllegalArgumentException("ING_QUARANTINE_STATE_INVALID");return sql.sql("select quarantine_id,run_id,attempt_id,source_object_id,reason_code,evidence_ref,state,correlation_id,created_at,resolved_at from ouf_ingestion.ing_quarantine where state=:s order by created_at desc limit :n").param("s",state).param("n",Math.max(1,Math.min(limit,200))).query().listOfRows();}
  public Map<String,Object> get(UUID id){return sql.sql("select quarantine_id,run_id,attempt_id,source_object_id,reason_code,evidence_ref,state,correlation_id,created_at,resolved_at from ouf_ingestion.ing_quarantine where quarantine_id=:i").param("i",id).query().singleRow();}
  @Transactional public UUID quarantine(UUID run,UUID attempt,String sourceObject,String reason,String payloadRef,String evidenceRef,String correlation){UUID id=UUID.randomUUID();sql.sql("insert into ouf_ingestion.ing_quarantine(quarantine_id,run_id,attempt_id,source_object_id,reason_code,payload_ref,evidence_ref,correlation_id) values(:i,:r,:a,:o,:c,:p,:e,:x)").param("i",id).param("r",run).param("a",attempt).param("o",sourceObject).param("c",safe(reason)).param("p",payloadRef).param("e",evidenceRef).param("x",correlation).update();metrics.quarantine(reason);LOG.atWarn().addKeyValue("event","RECORD_QUARANTINED").addKeyValue("quarantineId",id).addKeyValue("runId",run).addKeyValue("errorCode",safe(reason)).addKeyValue("correlationId",correlation).log("Ingestion record quarantined");return id;}
  @Transactional public UUID requestReplay(UUID quarantineId,String bundleRef,TrustedAuthorizationContext.Context actor,String correlation){if(bundleRef==null||bundleRef.isBlank())throw new IllegalArgumentException("ING_REPLAY_BUNDLE_REQUIRED");Map<String,Object> q=get(quarantineId);if(!"OPEN".equals(q.get("state")))throw new IllegalStateException("ING_QUARANTINE_NOT_OPEN");UUID replay=UUID.randomUUID();sql.sql("insert into ouf_ingestion.replay_request(replay_id,quarantine_id,requested_by,capability,target_bundle_ref,correlation_id,tenant_id,authorization_decision_ref) values(:r,:q,:a,'ingestion.quarantine.replay',:b,:c,:t,:d)").param("r",replay).param("q",quarantineId).param("a",actor.subject()).param("b",bundleRef).param("c",correlation).param("t",actor.tenantId()).param("d",actor.decisionRef()).update();sql.sql("insert into ouf_ingestion.replay_execution(replay_id) values(:r)").param("r",replay).update();sql.sql("update ouf_ingestion.ing_quarantine set state='REPLAY_REQUESTED' where quarantine_id=:q and state='OPEN'").param("q",quarantineId).update();audit("QUARANTINE_REPLAY_REQUESTED",actor,"QUARANTINE",quarantineId.toString(),correlation,Map.of("replayId",replay,"targetBundleRef",bundleRef));metrics.replay("requested");return replay;}
  private void audit(String type,TrustedAuthorizationContext.Context actor,String resource,String id,String correlation,Map<String,Object> detail){try{sql.sql("insert into ouf_ingestion.audit_event(event_id,event_type,actor_subject,actor_type,resource_type,resource_id,correlation_id,detail_json,tenant_id,authorization_decision_ref) values(:i,:e,:a,:t,:r,:x,:c,cast(:j as jsonb),:n,:d)").param("i",UUID.randomUUID()).param("e",type).param("a",actor.subject()).param("t",actor.actorType()).param("r",resource).param("x",id).param("c",correlation).param("j",json.writeValueAsString(detail)).param("n",actor.tenantId()).param("d",actor.decisionRef()).update();}catch(Exception e){throw new IllegalStateException("ING_AUDIT_WRITE_FAILED",e);}}
  private static String safe(String code){if(code==null||!code.matches("[A-Z0-9_]{1,80}"))throw new IllegalArgumentException("ING_REASON_CODE_INVALID");return code;}
}
