package it.comune.trieste.ouf.ingestion;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import org.slf4j.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class QuarantineService {
  private static final Logger LOG=LoggerFactory.getLogger(QuarantineService.class);
  private final JdbcClient sql;private final ObjectMapper json;private final IngestionMetrics metrics;
  public QuarantineService(JdbcClient sql,ObjectMapper json,IngestionMetrics metrics){this.sql=sql;this.json=json;this.metrics=metrics;}
  public List<Map<String,Object>> search(String state,int limit){if(!lifecycleStates().contains(state))throw new IllegalArgumentException("ING_QUARANTINE_STATE_INVALID");return sql.sql("select quarantine_id,run_id,attempt_id,source_object_id,reason_code,evidence_ref,state,lifecycle_state,lifecycle_version,correlation_id,created_at,resolved_at from ouf_ingestion.ing_quarantine where lifecycle_state=:s order by created_at desc limit :n").param("s",state).param("n",Math.max(1,Math.min(limit,200))).query().listOfRows();}
  public List<Map<String,Object>> search(String state,int limit,TrustedAuthorizationContext.Context actor){if(!lifecycleStates().contains(state))throw new IllegalArgumentException("ING_QUARANTINE_STATE_INVALID");return sql.sql("select q.quarantine_id,q.run_id,q.attempt_id,q.reason_code,q.evidence_ref,q.state,q.lifecycle_state,q.lifecycle_version,q.correlation_id,q.created_at,q.resolved_at from ouf_ingestion.ing_quarantine q join ouf_ingestion.ing_run r on r.run_id=q.run_id where q.lifecycle_state=:s and r.tenant_id=:t order by q.created_at desc limit :n").param("s",state).param("t",actor.tenantId()).param("n",Math.max(1,Math.min(limit,200))).query().listOfRows();}
  public Map<String,Object> get(UUID id){return sql.sql("select quarantine_id,run_id,attempt_id,source_object_id,reason_code,evidence_ref,state,lifecycle_state,lifecycle_version,resolution_reason,resolution_actor,superseded_by,correlation_id,created_at,resolved_at from ouf_ingestion.ing_quarantine where quarantine_id=:i").param("i",id).query().singleRow();}
  public Map<String,Object> get(UUID id,TrustedAuthorizationContext.Context actor){Map<String,Object> q=new LinkedHashMap<>(tenantGet(id,actor));q.remove("payload_ref");q.remove("authorization_decision_ref");return q;}
  public Map<String,Object> preview(UUID id,TrustedAuthorizationContext.Context actor){Map<String,Object> q=tenantGet(id,actor);Map<String,Object> safe=new LinkedHashMap<>();safe.put("quarantineId",q.get("quarantine_id"));safe.put("runId",q.get("run_id"));safe.put("attemptId",q.get("attempt_id"));safe.put("sourceObjectFingerprint",fingerprint(String.valueOf(q.get("source_object_id"))));safe.put("reasonCode",q.get("reason_code"));safe.put("evidenceRef",q.get("evidence_ref"));safe.put("lifecycleState",q.get("lifecycle_state"));safe.put("lifecycleVersion",q.get("lifecycle_version"));safe.put("createdAt",q.get("created_at"));return safe;}
  @Transactional public UUID quarantine(UUID run,UUID attempt,String sourceObject,String reason,String payloadRef,String evidenceRef,String correlation){UUID id=UUID.randomUUID();sql.sql("insert into ouf_ingestion.ing_quarantine(quarantine_id,run_id,attempt_id,source_object_id,reason_code,payload_ref,evidence_ref,correlation_id) values(:i,:r,:a,:o,:c,:p,:e,:x)").param("i",id).param("r",run).param("a",attempt).param("o",sourceObject).param("c",safe(reason)).param("p",payloadRef).param("e",evidenceRef).param("x",correlation).update();sql.sql("insert into ouf_ingestion.runtime_issue(issue_id,run_id,source_id,type_code,severity,issue_code,evidence_ref,correlation_id,quarantine_id) select :i,r.run_id,r.source_id,coalesce(s.snapshot_json#>>'{configuration,typeCode}','UNKNOWN'),'ERROR','ING_QUARANTINE_ITEM',:e,:c,:q from ouf_ingestion.ing_run r left join ouf_ingestion.runtime_configuration_snapshot s on s.run_id=r.run_id where r.run_id=:r").param("i",UUID.randomUUID()).param("e",id.toString()).param("c",correlation).param("q",id).param("r",run).update();metrics.quarantine(reason);LOG.atWarn().addKeyValue("event","RECORD_QUARANTINED").addKeyValue("quarantineId",id).addKeyValue("runId",run).addKeyValue("errorCode",safe(reason)).addKeyValue("correlationId",correlation).log("Ingestion record quarantined");return id;}
  @Transactional public void markRetryReady(UUID id,long expectedVersion,TrustedAuthorizationContext.Context actor,String correlation){int n=sql.sql("update ouf_ingestion.ing_quarantine q set lifecycle_state='RETRY_READY',lifecycle_version=lifecycle_version+1,authorization_decision_ref=:d from ouf_ingestion.ing_run r where q.quarantine_id=:i and r.run_id=q.run_id and r.tenant_id=:t and q.lifecycle_state='OPEN' and q.lifecycle_version=:v").param("d",actor.decisionRef()).param("i",id).param("t",actor.tenantId()).param("v",expectedVersion).update();if(n!=1)throw new IllegalStateException("ING_QUARANTINE_STATE_CONFLICT");audit("QUARANTINE_RETRY_READY",actor,"QUARANTINE",id.toString(),correlation,Map.of("expectedVersion",expectedVersion));}
  @Transactional public UUID prepareAndReplay(UUID quarantineId,String bundleRef,TrustedAuthorizationContext.Context actor,String correlation){Map<String,Object> q=tenantGet(quarantineId,actor);if("OPEN".equals(q.get("lifecycle_state")))markRetryReady(quarantineId,number(q.get("lifecycle_version")),actor,correlation);return requestReplay(quarantineId,bundleRef,actor,correlation);}
  @Transactional public UUID requestReplay(UUID quarantineId,String bundleRef,TrustedAuthorizationContext.Context actor,String correlation){if(bundleRef==null||bundleRef.isBlank())throw new IllegalArgumentException("ING_REPLAY_BUNDLE_REQUIRED");Map<String,Object> q=tenantGet(quarantineId,actor);if(!"RETRY_READY".equals(q.get("lifecycle_state")))throw new IllegalStateException("ING_QUARANTINE_NOT_RETRY_READY");UUID replay=UUID.randomUUID();sql.sql("insert into ouf_ingestion.replay_request(replay_id,quarantine_id,requested_by,capability,target_bundle_ref,correlation_id,tenant_id,authorization_decision_ref) values(:r,:q,:a,'ouf.ingestion.quarantine.reprocess',:b,:c,:t,:d)").param("r",replay).param("q",quarantineId).param("a",actor.subject()).param("b",bundleRef).param("c",correlation).param("t",actor.tenantId()).param("d",actor.decisionRef()).update();sql.sql("insert into ouf_ingestion.replay_execution(replay_id) values(:r)").param("r",replay).update();int n=sql.sql("update ouf_ingestion.ing_quarantine set state='REPLAY_REQUESTED',lifecycle_state='REPROCESSING',lifecycle_version=lifecycle_version+1 where quarantine_id=:q and lifecycle_version=:v and lifecycle_state='RETRY_READY'").param("q",quarantineId).param("v",number(q.get("lifecycle_version"))).update();if(n!=1)throw new IllegalStateException("ING_QUARANTINE_STATE_CONFLICT");audit("QUARANTINE_REPROCESSING",actor,"QUARANTINE",quarantineId.toString(),correlation,Map.of("replayId",replay,"targetBundleRef",bundleRef));metrics.replay("requested");return replay;}
  @Transactional public void close(UUID id,String target,String reason,String supersededBy,long expectedVersion,TrustedAuthorizationContext.Context actor,String correlation){if(!Set.of("DISMISSED","SUPERSEDED").contains(target)||reason==null||reason.isBlank()||reason.length()>1000||("SUPERSEDED".equals(target)&&(supersededBy==null||supersededBy.isBlank())))throw new IllegalArgumentException("ING_QUARANTINE_RESOLUTION_INVALID");int n=sql.sql("update ouf_ingestion.ing_quarantine q set state='REJECTED',lifecycle_state=:s,lifecycle_version=lifecycle_version+1,resolution_reason=:r,resolution_actor=:a,authorization_decision_ref=:d,superseded_by=:b,resolved_at=transaction_timestamp() from ouf_ingestion.ing_run run where q.quarantine_id=:i and run.run_id=q.run_id and run.tenant_id=:t and q.lifecycle_state='OPEN' and q.lifecycle_version=:v").param("s",target).param("r",reason).param("a",actor.subject()).param("d",actor.decisionRef()).param("b",supersededBy).param("i",id).param("t",actor.tenantId()).param("v",expectedVersion).update();if(n!=1)throw new IllegalStateException("ING_QUARANTINE_STATE_CONFLICT");audit("QUARANTINE_"+target,actor,"QUARANTINE",id.toString(),correlation,Map.of("reason",reason,"expectedVersion",expectedVersion));}
  private Map<String,Object> tenantGet(UUID id,TrustedAuthorizationContext.Context actor){List<Map<String,Object>> rows=sql.sql("select q.* from ouf_ingestion.ing_quarantine q join ouf_ingestion.ing_run r on r.run_id=q.run_id where q.quarantine_id=:i and r.tenant_id=:t").param("i",id).param("t",actor.tenantId()).query().listOfRows();if(rows.isEmpty())throw new NoSuchElementException("ING_QUARANTINE_NOT_FOUND");return rows.getFirst();}
  private void audit(String type,TrustedAuthorizationContext.Context actor,String resource,String id,String correlation,Map<String,Object> detail){try{sql.sql("insert into ouf_ingestion.audit_event(event_id,event_type,actor_subject,actor_type,resource_type,resource_id,correlation_id,detail_json,tenant_id,authorization_decision_ref) values(:i,:e,:a,:t,:r,:x,:c,cast(:j as jsonb),:n,:d)").param("i",UUID.randomUUID()).param("e",type).param("a",actor.subject()).param("t",actor.actorType()).param("r",resource).param("x",id).param("c",correlation).param("j",json.writeValueAsString(detail)).param("n",actor.tenantId()).param("d",actor.decisionRef()).update();}catch(Exception e){throw new IllegalStateException("ING_AUDIT_WRITE_FAILED",e);}}
  private static String safe(String code){if(code==null||!code.matches("[A-Z0-9_]{1,80}"))throw new IllegalArgumentException("ING_REASON_CODE_INVALID");return code;}
  private static Set<String> lifecycleStates(){return Set.of("OPEN","RETRY_READY","REPROCESSING","RESOLVED","DISMISSED","SUPERSEDED");}
  private static long number(Object value){return value instanceof Number n?n.longValue():Long.parseLong(String.valueOf(value));}
  private static String fingerprint(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException("ING_FINGERPRINT_FAILED",e);}}
}
