package it.comune.trieste.ouf.ingestion;

import java.time.Duration;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

@Repository
public class ReplayRepository {
  private final JdbcClient sql;public ReplayRepository(JdbcClient sql){this.sql=sql;}
  @Transactional public Optional<Claim> claim(String worker,Duration lease){Optional<Started> started=sql.sql("with candidate as (select replay_id from ouf_ingestion.replay_execution where ((state in ('QUEUED','RETRY_WAIT') and next_attempt_at<=transaction_timestamp()) or (state='RUNNING' and lease_until<transaction_timestamp())) and attempts<max_attempts order by next_attempt_at,replay_id for update skip locked limit 1), claimed as (update ouf_ingestion.replay_execution e set state='RUNNING',attempts=attempts+1,claimed_by=:w,lease_until=transaction_timestamp()+(:ms*interval '1 millisecond'),last_error_code=null,updated_at=transaction_timestamp() from candidate c where e.replay_id=c.replay_id returning e.replay_id,e.attempts) insert into ouf_ingestion.replay_attempt(replay_attempt_id,replay_id,attempt_no,worker_id,outcome) select gen_random_uuid(),c.replay_id,c.attempts,:w,'STARTED' from claimed c returning replay_id,attempt_no").param("w",worker).param("ms",lease.toMillis()).query((rs,n)->new Started(rs.getObject(1,UUID.class),rs.getInt(2))).optional();return started.map(s->details(s.replayId(),s.attemptNo(),worker));}
  @Transactional public void succeeded(Claim c,RuntimePorts.ReplayExecutionPort.Receipt receipt){if(!receipt.durable())throw new IllegalArgumentException("ING_REPLAY_OUTCOME_NOT_DURABLE");int n=sql.sql("update ouf_ingestion.replay_execution set state='SUCCEEDED',claimed_by=null,lease_until=null,result_attempt_id=:a,downstream_receipt_ref=:d,completed_at=transaction_timestamp(),updated_at=transaction_timestamp() where replay_id=:r and state='RUNNING' and claimed_by=:w and attempts=:n").param("a",receipt.processingAttemptId()).param("d",receipt.downstreamReceiptRef()).param("r",c.replayId()).param("w",c.worker()).param("n",c.attemptNo()).update();if(n!=1)throw new IllegalStateException("ING_REPLAY_LEASE_LOST");append(c,"SUCCEEDED",null,receipt.processingAttemptId());sql.sql("update ouf_ingestion.ing_quarantine set state='RELEASED',lifecycle_state='RESOLVED',lifecycle_version=lifecycle_version+1,resolved_at=transaction_timestamp() where quarantine_id=:q and lifecycle_state='REPROCESSING'").param("q",c.quarantineId()).update();}
  @Transactional public void failed(Claim c,String code,Duration delay){String safe=safe(code);Map<String,Object> current=sql.sql("select attempts,max_attempts from ouf_ingestion.replay_execution where replay_id=:r and state='RUNNING' and claimed_by=:w for update").param("r",c.replayId()).param("w",c.worker()).query().singleRow();boolean terminal=((Number)current.get("attempts")).intValue()>=((Number)current.get("max_attempts")).intValue();String state=terminal?"FAILED":"RETRY_WAIT",outcome=terminal?"FAILED_TERMINAL":"FAILED_RETRYABLE";sql.sql("update ouf_ingestion.replay_execution set state=:s,claimed_by=null,lease_until=null,next_attempt_at=transaction_timestamp()+(:ms*interval '1 millisecond'),last_error_code=:c,completed_at=case when :terminal then transaction_timestamp() else null end,updated_at=transaction_timestamp() where replay_id=:r").param("s",state).param("ms",delay.toMillis()).param("c",safe).param("terminal",terminal).param("r",c.replayId()).update();append(c,outcome,safe,null);if(terminal)sql.sql("update ouf_ingestion.ing_quarantine set state='OPEN',lifecycle_state='OPEN',lifecycle_version=lifecycle_version+1 where quarantine_id=:q and lifecycle_state='REPROCESSING'").param("q",c.quarantineId()).update();}
  public Map<String,Object> view(UUID replay){return sql.sql("select r.replay_id,r.quarantine_id,r.replay_mode,r.original_run_id,r.original_bundle_ref,r.target_bundle_ref,r.raw_object_ref,r.parent_attempt_id,r.correlation_id,r.tenant_id,e.state,e.attempts,e.max_attempts,e.next_attempt_at,e.result_attempt_id,e.last_error_code,e.completed_at from ouf_ingestion.replay_request r join ouf_ingestion.replay_execution e using(replay_id) where r.replay_id=:r").param("r",replay).query().singleRow();}
  private Claim details(UUID replay,int attempt,String worker){Map<String,Object> r=sql.sql("select replay_id,quarantine_id,replay_mode,original_run_id,original_bundle_ref,target_bundle_ref,raw_object_ref,parent_attempt_id,correlation_id from ouf_ingestion.replay_request where replay_id=:r").param("r",replay).query().singleRow();return new Claim(replay,(UUID)r.get("quarantine_id"),String.valueOf(r.get("replay_mode")),(UUID)r.get("original_run_id"),String.valueOf(r.get("original_bundle_ref")),String.valueOf(r.get("target_bundle_ref")),String.valueOf(r.get("raw_object_ref")),(UUID)r.get("parent_attempt_id"),String.valueOf(r.get("correlation_id")),attempt,worker);}
  private void append(Claim c,String outcome,String code,UUID attempt){sql.sql("insert into ouf_ingestion.replay_attempt(replay_attempt_id,replay_id,attempt_no,worker_id,outcome,safe_error_code,processing_attempt_id) values(:i,:r,:n,:w,:o,:c,:a)").param("i",UUID.randomUUID()).param("r",c.replayId()).param("n",c.attemptNo()).param("w",c.worker()).param("o",outcome).param("c",code).param("a",attempt).update();}
  private static String safe(String code){return code!=null&&code.matches("[A-Z0-9_]{1,80}")?code:"ING_REPLAY_FAILED";}
  private record Started(UUID replayId,int attemptNo){}
  public record Claim(UUID replayId,UUID quarantineId,String replayMode,UUID originalRunId,String originalBundleRef,String targetBundleRef,String rawObjectRef,UUID parentAttemptId,String correlationId,int attemptNo,String worker){}
}
