package it.comune.trieste.ouf.ingestion;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.transaction.PlatformTransactionManager;

/** Governed PAUSE/RESUME/ABORT preserving the pinned baseline and durable progress. */
@Service @ConditionalOnBean(RuntimePorts.SemanticPort.class)
public class RunLifecycleService {
  private final JdbcClient sql;private final ObjectMapper json;private final RuntimePorts.SemanticPort contracts;private final TransactionTemplate transactions;
  public RunLifecycleService(JdbcClient sql,ObjectMapper json,RuntimePorts.SemanticPort contracts,PlatformTransactionManager manager){this.sql=sql;this.json=json;this.contracts=contracts;this.transactions=new TransactionTemplate(manager);}
  @Transactional public Map<String,Object> pause(UUID run,long version,TrustedAuthorizationContext.Context actor,String correlation){Map<String,Object> current=locked(run,actor);expectVersion(current,version);String state=String.valueOf(current.get("state"));if(Set.of("SUCCEEDED","COMPLETED_WITH_WARNINGS","FAILED","ABORTED").contains(state))throw new IllegalStateException("ING_RUN_TERMINAL");int n=sql.sql("update ouf_ingestion.ing_run set state='PAUSED',control_version=control_version+1,updated_at=transaction_timestamp() where run_id=:r and tenant_id=:t and control_version=:v").param("r",run).param("t",actor.tenantId()).param("v",version).update();changed(n);sql.sql("update ouf_ingestion.ing_partition set state='PAUSED',lease_owner=null,lease_until=null where run_id=:r and state<>'SUCCEEDED'").param("r",run).update();audit("RUN_PAUSED",run,actor,correlation,Map.of("previousState",state,"version",version));return view(run,actor);}
  public Map<String,Object> resume(UUID run,long version,TrustedAuthorizationContext.Context actor,String correlation){ExecutionBundle snapshot=snapshot(run,actor);contracts.preflight(snapshot);return transactions.execute(status->resumeVerified(run,version,actor,correlation));}
  private Map<String,Object> resumeVerified(UUID run,long version,TrustedAuthorizationContext.Context actor,String correlation){Map<String,Object> current=locked(run,actor);expectVersion(current,version);if(!"PAUSED".equals(current.get("state")))throw new IllegalStateException("ING_RUN_NOT_PAUSED");int n=sql.sql("update ouf_ingestion.ing_run set state='RUNNING',failure_code=null,control_version=control_version+1,updated_at=transaction_timestamp() where run_id=:r and tenant_id=:t and state='PAUSED' and control_version=:v").param("r",run).param("t",actor.tenantId()).param("v",version).update();changed(n);sql.sql("update ouf_ingestion.ing_partition set state='RUNNING',lease_owner=null,lease_until=null where run_id=:r and state='PAUSED'").param("r",run).update();audit("RUN_RESUMED",run,actor,correlation,Map.of("bundleRef",bundleRef(current),"version",version));return view(run,actor);}
  @Transactional public Map<String,Object> abort(UUID run,long version,TrustedAuthorizationContext.Context actor,String correlation){Map<String,Object> current=locked(run,actor);expectVersion(current,version);String state=String.valueOf(current.get("state"));if(Set.of("SUCCEEDED","COMPLETED_WITH_WARNINGS","FAILED","ABORTED").contains(state))throw new IllegalStateException("ING_RUN_TERMINAL");int n=sql.sql("update ouf_ingestion.ing_run set state='ABORTED',failure_code='ING_OPERATOR_ABORTED',control_version=control_version+1,updated_at=transaction_timestamp() where run_id=:r and tenant_id=:t and control_version=:v").param("r",run).param("t",actor.tenantId()).param("v",version).update();changed(n);sql.sql("update ouf_ingestion.ing_partition set state='ABORTED',lease_owner=null,lease_until=null where run_id=:r and state<>'SUCCEEDED'").param("r",run).update();audit("RUN_ABORTED",run,actor,correlation,Map.of("previousState",state,"version",version));return view(run,actor);}
  public Map<String,Object> view(UUID run,TrustedAuthorizationContext.Context actor){List<Map<String,Object>> rows=sql.sql("select run_id,source_id,bundle_id,bundle_version,bundle_checksum,mode,state,phase,failure_code,control_version,created_at,updated_at from ouf_ingestion.ing_run where run_id=:r and tenant_id=:t").param("r",run).param("t",actor.tenantId()).query().listOfRows();if(rows.isEmpty())throw new NoSuchElementException("ING_RUN_NOT_FOUND");return rows.getFirst();}
  private Map<String,Object> locked(UUID run,TrustedAuthorizationContext.Context actor){List<Map<String,Object>> rows=sql.sql("select run_id,bundle_id,bundle_version,bundle_checksum,state,control_version from ouf_ingestion.ing_run where run_id=:r and tenant_id=:t for update").param("r",run).param("t",actor.tenantId()).query().listOfRows();if(rows.isEmpty())throw new NoSuchElementException("ING_RUN_NOT_FOUND");return rows.getFirst();}
  private ExecutionBundle snapshot(UUID run,TrustedAuthorizationContext.Context actor){String raw=sql.sql("select s.snapshot_json::text from ouf_ingestion.runtime_configuration_snapshot s join ouf_ingestion.ing_run r using(run_id) where s.run_id=:r and r.tenant_id=:t and r.state='PAUSED'").param("r",run).param("t",actor.tenantId()).query(String.class).optional().orElseThrow(()->new IllegalStateException("ING_RUN_NOT_PAUSED"));try{return json.readValue(raw,ExecutionBundle.class);}catch(Exception e){throw new IllegalStateException("ING_BUNDLE_SNAPSHOT_INVALID",e);}}
  private static Collection<String> pinned(ExecutionBundle bundle){Object value=bundle.configuration().get("pinnedReferences");if(!(value instanceof Collection<?> refs)||refs.isEmpty())throw new IllegalStateException("ING_PREFLIGHT_REFS_REQUIRED");return refs.stream().map(String::valueOf).toList();}
  private void audit(String event,UUID run,TrustedAuthorizationContext.Context actor,String correlation,Map<String,Object> detail){try{sql.sql("insert into ouf_ingestion.audit_event(event_id,event_type,actor_subject,actor_type,resource_type,resource_id,correlation_id,detail_json,tenant_id,authorization_decision_ref) values(:i,:e,:a,:t,'RUN',:r,:c,cast(:j as jsonb),:n,:d)").param("i",UUID.randomUUID()).param("e",event).param("a",actor.subject()).param("t",actor.actorType()).param("r",run.toString()).param("c",correlation).param("j",json.writeValueAsString(detail)).param("n",actor.tenantId()).param("d",actor.decisionRef()).update();}catch(Exception e){throw new IllegalStateException("ING_AUDIT_WRITE_FAILED",e);}}
  private static String bundleRef(Map<String,Object> row){return row.get("bundle_id")+":"+row.get("bundle_version")+":"+row.get("bundle_checksum");}
  private static void expectVersion(Map<String,Object> row,long version){if(((Number)row.get("control_version")).longValue()!=version)throw new IllegalStateException("ING_RUN_STATE_CONFLICT");}
  private static void changed(int n){if(n!=1)throw new IllegalStateException("ING_RUN_STATE_CONFLICT");}
}
