package it.comune.trieste.ouf.ingestion;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service
public class RuntimeIssueService {
  private final JdbcClient sql;private final ObjectMapper json;
  public RuntimeIssueService(JdbcClient sql,ObjectMapper json){this.sql=sql;this.json=json;}
  public List<Map<String,Object>> search(String state,String severity,String source,UUID run,int limit,TrustedAuthorizationContext.Context actor){validate(state,severity);return sql.sql("select i.issue_id,i.run_id,i.source_id,i.type_code,i.severity,i.issue_code,i.evidence_ref,i.status,i.lock_version,i.quarantine_id,i.onboarding_review_ref,i.created_at,i.resolved_at from ouf_ingestion.runtime_issue i join ouf_ingestion.ing_run r on r.run_id=i.run_id where r.tenant_id=:t and (cast(:s as text) is null or i.status=:s) and (cast(:v as text) is null or i.severity=:v) and (cast(:o as text) is null or i.source_id=:o) and (cast(:r as uuid) is null or i.run_id=:r) order by i.created_at desc limit :n").param("t",actor.tenantId()).param("s",state).param("v",severity).param("o",source).param("r",run).param("n",Math.max(1,Math.min(limit,200))).query().listOfRows();}
  public Map<String,Object> get(UUID id,TrustedAuthorizationContext.Context actor){List<Map<String,Object>> rows=sql.sql("select i.issue_id,i.run_id,i.source_id,i.type_code,i.severity,i.issue_code,i.evidence_ref,i.status,i.lock_version,i.quarantine_id,i.onboarding_review_ref,i.resolution_reason,i.created_at,i.resolved_at from ouf_ingestion.runtime_issue i join ouf_ingestion.ing_run r on r.run_id=i.run_id where i.issue_id=:i and r.tenant_id=:t").param("i",id).param("t",actor.tenantId()).query().listOfRows();if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"ING_ISSUE_NOT_FOUND");return rows.getFirst();}
  public Map<String,Object> explain(UUID id,TrustedAuthorizationContext.Context actor){Map<String,Object> issue=get(id,actor);String code=String.valueOf(issue.get("issue_code"));String action=switch(code){case "ING_SCHEMA_INCOMPATIBLE","ING_SCHEMA_UNKNOWN_VERSION"->"REQUEST_ONBOARDING_REVIEW";case "ING_QUARANTINE_ITEM"->"INSPECT_QUARANTINE_AND_REPROCESS";default->"INSPECT_RUN_EVIDENCE";};Map<String,Object> result=new LinkedHashMap<>();result.put("issueId",issue.get("issue_id"));result.put("classification",code);result.put("severity",issue.get("severity"));result.put("status",issue.get("status"));result.put("evidenceRef",issue.get("evidence_ref"));result.put("quarantineId",issue.get("quarantine_id"));result.put("recommendedAction",action);result.put("explanationCode","EXPLAIN_"+code);return result;}
  public List<Map<String,Object>> observations(String source,String outcome,int limit,TrustedAuthorizationContext.Context actor){if(outcome!=null&&!Set.of("MATCH","COMPATIBLE_ADDITIVE","UNKNOWN_VERSION","INCOMPATIBLE").contains(outcome))throw new IllegalArgumentException("ING_SCHEMA_OUTCOME_INVALID");return sql.sql("select o.observation_id,o.run_id,o.source_id,o.type_code,o.schema_checksum,o.outcome,o.expected_schema_version,o.observed_schema_version,o.field_names,o.observation_count,o.first_observed_at,o.last_observed_at from ouf_ingestion.schema_observation o join ouf_ingestion.ing_run r on r.run_id=o.run_id where r.tenant_id=:t and (cast(:s as text) is null or o.source_id=:s) and (cast(:o as text) is null or o.outcome=:o) order by o.last_observed_at desc limit :n").param("t",actor.tenantId()).param("s",source).param("o",outcome).param("n",Math.max(1,Math.min(limit,200))).query().listOfRows();}
  @Transactional public void close(UUID id,String target,String reason,long expectedVersion,TrustedAuthorizationContext.Context actor,String correlation){if(!Set.of("RESOLVED","DISMISSED").contains(target)||reason==null||reason.isBlank()||reason.length()>1000)throw new IllegalArgumentException("ING_ISSUE_RESOLUTION_INVALID");int n=sql.sql("update ouf_ingestion.runtime_issue i set status=:s,resolution_reason=:x,resolution_actor=:a,authorization_decision_ref=:d,resolved_at=transaction_timestamp(),lock_version=lock_version+1 from ouf_ingestion.ing_run r where i.issue_id=:i and r.run_id=i.run_id and r.tenant_id=:t and i.status='OPEN' and i.lock_version=:v").param("s",target).param("x",reason).param("a",actor.subject()).param("d",actor.decisionRef()).param("i",id).param("t",actor.tenantId()).param("v",expectedVersion).update();if(n!=1)throw new ResponseStatusException(HttpStatus.CONFLICT,"ING_ISSUE_STATE_CONFLICT");audit("RUNTIME_ISSUE_"+target,actor,id,correlation,Map.of("reason",reason,"expectedVersion",expectedVersion));}
  @Transactional public UUID requestOnboardingReview(UUID id,long expectedVersion,TrustedAuthorizationContext.Context actor,String correlation){Map<String,Object> issue=get(id,actor);if(!"OPEN".equals(issue.get("status"))||number(issue.get("lock_version"))!=expectedVersion)throw new ResponseStatusException(HttpStatus.CONFLICT,"ING_ISSUE_STATE_CONFLICT");UUID request=UUID.randomUUID();String key="ingestion-issue:"+id+":"+expectedVersion;UUID queued=sql.sql("insert into ouf_ingestion.onboarding_review_outbox(request_id,issue_id,idempotency_key,correlation_id) values(:r,:i,:k,:c) on conflict(idempotency_key) do update set correlation_id=onboarding_review_outbox.correlation_id returning request_id").param("r",request).param("i",id).param("k",key).param("c",correlation).query(UUID.class).single();audit("ONBOARDING_REVIEW_QUEUED",actor,id,correlation,Map.of("requestId",queued));return queued;}
  private void audit(String type,TrustedAuthorizationContext.Context a,UUID id,String correlation,Map<String,Object> detail){try{sql.sql("insert into ouf_ingestion.audit_event(event_id,event_type,actor_subject,actor_type,resource_type,resource_id,correlation_id,detail_json,tenant_id,authorization_decision_ref) values(:i,:e,:a,:t,'RUNTIME_ISSUE',:r,:c,cast(:j as jsonb),:n,:d)").param("i",UUID.randomUUID()).param("e",type).param("a",a.subject()).param("t",a.actorType()).param("r",id.toString()).param("c",correlation).param("j",json.writeValueAsString(detail)).param("n",a.tenantId()).param("d",a.decisionRef()).update();}catch(Exception e){throw new IllegalStateException("ING_AUDIT_WRITE_FAILED",e);}}
  private static void validate(String state,String severity){if(state!=null&&!Set.of("OPEN","RESOLVED","DISMISSED").contains(state))throw new IllegalArgumentException("ING_ISSUE_STATE_INVALID");if(severity!=null&&!Set.of("WARNING","ERROR").contains(severity))throw new IllegalArgumentException("ING_ISSUE_SEVERITY_INVALID");}
  private static long number(Object v){return v instanceof Number n?n.longValue():Long.parseLong(String.valueOf(v));}
}
